title: Krish Iyer
description: [My Bio]

# Site Settings
locale                   : "en"
title                    : "krish7919.github.io"
title_separator          : "-"
name                     : "Krishnan Iyer"
description              : "Personal Website."
url                      : https://krish7919.github.io
repository               : krish7919/krish7919.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

# Site Author
author:
  name             : "Krishnan Iyer"
  avatar           : ""
  bio              : "I get things done"
  location         : "Berlin, Germany"
  email            : "jobs.for.krish7919@gmail.com"
  github           : "krish7919"
  linkedin         : "krish7919"
  stackoverflow    : "880963/krish7919"
  twitter          : "krish7919"

# Reading Files
#include:
#  - .htaccess
#  - _pages
#  - _posts
#exclude:
#  - "*.sublime-project"
#  - "*.sublime-workspace"
#  - vendor
#  - .asset-cache
#  - .bundle
#  - .jekyll-assets-cache
#  - .sass-cache
#  - assets/js/plugins
#  - assets/js/_main.js
#  - assets/js/vendor
#  - Capfile
#  - CHANGELOG
#  - config
#  - Gemfile
#  - Gruntfile.js
#  - gulpfile.js
#  - LICENSE
#  - log
#  - node_modules
#  - package.json
#  - Rakefile
#  - README
#  - tmp
#keep_files:
#  - .git
#  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

## Conversion - I do not use md
#markdown: kramdown
#highlighter: rouge
#lsi: false
#excerpt_separator: "\n\n"
#incremental: false

# Markdown Processing
#kramdown:
#  input: GFM
#  hard_wrap: false
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  smart_quotes: lsquo,rsquo,ldquo,rdquo
#  enable_coderay: false

# Plugins
#gems:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji
#  - jekyll-github-metadata

# mimic GitHub Pages with --safe
#whitelist:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
